using Microsoft.Practices.Prism.Mvvm;
using System.Windows;
using System.Windows.Controls;

namespace WebDB.Client.Prism.Modules.EntityGrid.Views
{
    /// <summary>
    /// Interaction logic for UserControl1.xaml
    /// </summary>
    public partial class EntityGridView : UserControl, IView, IEntityGridView
    {
        public EntityGridView()
        {
            InitializeComponent();
        }

        private void UserControl_DataContextChanged(object sender, System.Windows.DependencyPropertyChangedEventArgs e)
        {
            //Binding binding = new Binding() { Path = new PropertyPath("Items"), Source = this.DataContext };

            //DataGrid listView = new DataGrid() { AutoGenerateColumns = true };// { AutoCreateColumns = true };
            ////BindingOperations.SetBinding(listView, DataGrid.ItemsSourceProperty, binding);
            //listView.ItemsSource = (DataContext as EntityGridViewModel).Items;
            //stackPanel.Children.Add(listView);


            //var source = dataGridControl.ItemsSource;
            //dataGridControl.ItemsSource = null;
            //dataGridControl.ItemsSource = source;
        }

        private void devDataGrid_SelectedItemChanged(object sender, DevExpress.Xpf.Grid.SelectedItemChangedEventArgs e)
        {

        }

        private void devDataGrid_AutoGeneratedColumns(object sender, System.Windows.RoutedEventArgs e)
        {
            foreach(var column in devDataGrid.Columns)
            {
                //if (typeof(Model.ModelObjectBase).IsAssignableFrom(column.FieldType))
                //{
                //    column.Binding = new System.Windows.Data.Binding($"{column.Name}.DesignerId");
                //    column.Binding = new System.Windows.Data.Binding($"DesignerId");
                //}
                //if (column.Binding != null)
                //    column.Binding.StringFormat = "{DisplayId}";
            }
        }

        private void devDataGrid_AutoGeneratingColumn(object sender, DevExpress.Xpf.Grid.AutoGeneratingColumnEventArgs e)
        {
            if (typeof(Model.ModelObjectBase).IsAssignableFrom(e.Column.FieldType))
            {
                //e.Column.Binding = new System.Windows.Data.Binding($"{e.Column.Name}.DesignerId");
                e.Column.CellTemplate = (DataTemplate)this.Resources["temp"];
                
                //e.Column.DisplayTemplate.Template = new System.Windows.TemplateContent()
            }
        }
    }
}
